// A small curated set of well-known UK golf courses, used to prefill the
// "add a course" admin form. Par, stroke index, course rating and slope
// rating are taken from published club scorecards for the tee noted below.
// Course/slope rating and stroke indexes can be revised by a club, so the
// admin form leaves every field editable after prefill — treat this as a
// starting point to check against the current scorecard, not a source of
// truth.
const UK_COURSES = [
  {
    id: 'st-andrews-old',
    name: 'St Andrews Links – The Old Course',
    region: 'Fife, Scotland',
    teeName: 'Yellow',
    courseRating: 71.4,
    slopeRating: 129,
    holes: [
      { par: 4, si: 10 },
      { par: 4, si: 6 },
      { par: 4, si: 16 },
      { par: 4, si: 8 },
      { par: 5, si: 2 },
      { par: 4, si: 12 },
      { par: 4, si: 4 },
      { par: 3, si: 14 },
      { par: 4, si: 18 },
      { par: 4, si: 15 },
      { par: 3, si: 7 },
      { par: 4, si: 3 },
      { par: 4, si: 11 },
      { par: 5, si: 1 },
      { par: 4, si: 9 },
      { par: 4, si: 13 },
      { par: 4, si: 5 },
      { par: 4, si: 17 },
    ],
  },
  {
    id: 'carnoustie-championship',
    name: 'Carnoustie Golf Links – Championship Course',
    region: 'Angus, Scotland',
    teeName: 'White',
    courseRating: 75.2,
    slopeRating: 139,
    holes: [
      { par: 4, si: 10 },
      { par: 4, si: 4 },
      { par: 4, si: 14 },
      { par: 4, si: 16 },
      { par: 4, si: 12 },
      { par: 5, si: 2 },
      { par: 4, si: 8 },
      { par: 3, si: 18 },
      { par: 4, si: 6 },
      { par: 4, si: 3 },
      { par: 4, si: 15 },
      { par: 5, si: 9 },
      { par: 3, si: 17 },
      { par: 5, si: 1 },
      { par: 4, si: 7 },
      { par: 3, si: 13 },
      { par: 4, si: 5 },
      { par: 4, si: 11 },
    ],
  },
  {
    id: 'royal-st-georges',
    name: "Royal St George's Golf Club",
    region: 'Sandwich, Kent, England',
    teeName: 'Yellow',
    courseRating: 71.0,
    slopeRating: 129,
    holes: [
      { par: 4, si: 10 },
      { par: 4, si: 6 },
      { par: 3, si: 16 },
      { par: 4, si: 2 },
      { par: 4, si: 8 },
      { par: 3, si: 18 },
      { par: 5, si: 14 },
      { par: 4, si: 4 },
      { par: 4, si: 12 },
      { par: 4, si: 9 },
      { par: 3, si: 3 },
      { par: 4, si: 15 },
      { par: 4, si: 7 },
      { par: 5, si: 13 },
      { par: 4, si: 1 },
      { par: 3, si: 17 },
      { par: 4, si: 5 },
      { par: 4, si: 11 },
    ],
  },
];

module.exports = { UK_COURSES };
