// A small curated set of well-known UK golf courses, used to prefill the
// "add a course" admin form. Par, stroke index, course rating and slope
// rating are taken from published club scorecards for the tee noted below.
// Course/slope rating and stroke indexes can be revised by a club, so the
// admin form leaves every field editable after prefill — treat this as a
// starting point to check against the current scorecard, not a source of
// truth.
const UK_COURSES = [
  {
    id: 'st-andrews-old',
    name: 'St Andrews Links – The Old Course',
    region: 'Fife, Scotland',
    teeName: 'Yellow',
    courseRating: 71.4,
    slopeRating: 129,
    holes: [
      { par: 4, si: 10 },
      { par: 4, si: 6 },
      { par: 4, si: 16 },
      { par: 4, si: 8 },
      { par: 5, si: 2 },
      { par: 4, si: 12 },
      { par: 4, si: 4 },
      { par: 3, si: 14 },
      { par: 4, si: 18 },
      { par: 4, si: 15 },
      { par: 3, si: 7 },
      { par: 4, si: 3 },
      { par: 4, si: 11 },
      { par: 5, si: 1 },
      { par: 4, si: 9 },
      { par: 4, si: 13 },
      { par: 4, si: 5 },
      { par: 4, si: 17 },
    ],
  },
  {
    id: 'carnoustie-championship',
    name: 'Carnoustie Golf Links – Championship Course',
    region: 'Angus, Scotland',
    teeName: 'White',
    courseRating: 75.2,
    slopeRating: 139,
    holes: [
      { par: 4, si: 10 },
      { par: 4, si: 4 },
      { par: 4, si: 14 },
      { par: 4, si: 16 },
      { par: 4, si: 12 },
      { par: 5, si: 2 },
      { par: 4, si: 8 },
      { par: 3, si: 18 },
      { par: 4, si: 6 },
      { par: 4, si: 3 },
      { par: 4, si: 15 },
      { par: 5, si: 9 },
      { par: 3, si: 17 },
      { par: 5, si: 1 },
      { par: 4, si: 7 },
      { par: 3, si: 13 },
      { par: 4, si: 5 },
      { par: 4, si: 11 },
    ],
  },
  {
    id: 'royal-st-georges',
    name: "Royal St George's Golf Club",
    region: 'Sandwich, Kent, England',
    teeName: 'Yellow',
    courseRating: 71.0,
    slopeRating: 129,
    holes: [
      { par: 4, si: 10 },
      { par: 4, si: 6 },
      { par: 3, si: 16 },
      { par: 4, si: 2 },
      { par: 4, si: 8 },
      { par: 3, si: 18 },
      { par: 5, si: 14 },
      { par: 4, si: 4 },
      { par: 4, si: 12 },
      { par: 4, si: 9 },
      { par: 3, si: 3 },
      { par: 4, si: 15 },
      { par: 4, si: 7 },
      { par: 5, si: 13 },
      { par: 4, si: 1 },
      { par: 3, si: 17 },
      { par: 4, si: 5 },
      { par: 4, si: 11 },
    ],
  },
  {
    id: 'royal-troon-old',
    name: 'Royal Troon Golf Club — Old Course',
    region: 'South Ayrshire, Scotland',
    teeName: 'White',
    courseRating: 73.4,
    slopeRating: 140,
    holes: [
      { par: 4, si: 16 },
      { par: 4, si: 7 },
      { par: 4, si: 11 },
      { par: 5, si: 4 },
      { par: 3, si: 14 },
      { par: 5, si: 2 },
      { par: 4, si: 9 },
      { par: 3, si: 18 },
      { par: 4, si: 5 },
      { par: 4, si: 10 },
      { par: 4, si: 1 },
      { par: 4, si: 6 },
      { par: 4, si: 12 },
      { par: 3, si: 15 },
      { par: 4, si: 3 },
      { par: 5, si: 8 },
      { par: 3, si: 13 },
      { par: 4, si: 17 },
    ],
  },
  {
    id: 'muirfield',
    name: 'Muirfield — The Honourable Company of Edinburgh Golfers',
    region: 'East Lothian, Scotland',
    teeName: 'White',
    courseRating: 72.5,
    slopeRating: 139,
    holes: [
      { par: 4, si: 5 },
      { par: 4, si: 17 },
      { par: 4, si: 11 },
      { par: 3, si: 13 },
      { par: 5, si: 7 },
      { par: 4, si: 3 },
      { par: 3, si: 15 },
      { par: 4, si: 1 },
      { par: 5, si: 9 },
      { par: 4, si: 4 },
      { par: 4, si: 18 },
      { par: 4, si: 16 },
      { par: 3, si: 14 },
      { par: 4, si: 2 },
      { par: 4, si: 8 },
      { par: 3, si: 12 },
      { par: 5, si: 10 },
      { par: 4, si: 6 },
    ],
  },
  {
    id: 'wentworth-club-west',
    name: 'Wentworth Club — West Course',
    region: 'Surrey, England',
    teeName: 'Yellow',
    courseRating: 74.2,
    slopeRating: 148,
    holes: [
      { par: 5, si: 16 },
      { par: 3, si: 14 },
      { par: 4, si: 2 },
      { par: 5, si: 18 },
      { par: 3, si: 8 },
      { par: 4, si: 12 },
      { par: 4, si: 10 },
      { par: 4, si: 6 },
      { par: 4, si: 4 },
      { par: 3, si: 7 },
      { par: 4, si: 11 },
      { par: 5, si: 17 },
      { par: 4, si: 3 },
      { par: 3, si: 9 },
      { par: 4, si: 1 },
      { par: 4, si: 5 },
      { par: 5, si: 13 },
      { par: 5, si: 15 },
    ],
  },
  {
    id: 'gleneagles-pga-centenary',
    name: 'The Gleneagles Hotel — PGA Centenary Course',
    region: 'Auchterarder, Perthshire, Scotland',
    teeName: 'White',
    courseRating: 74.2,
    slopeRating: 138,
    holes: [
      { par: 4, si: 9 },
      { par: 5, si: 7 },
      { par: 4, si: 3 },
      { par: 3, si: 13 },
      { par: 4, si: 1 },
      { par: 3, si: 15 },
      { par: 4, si: 5 },
      { par: 4, si: 17 },
      { par: 5, si: 11 },
      { par: 3, si: 12 },
      { par: 4, si: 16 },
      { par: 4, si: 6 },
      { par: 4, si: 2 },
      { par: 4, si: 14 },
      { par: 4, si: 4 },
      { par: 5, si: 8 },
      { par: 3, si: 18 },
      { par: 5, si: 10 },
    ],
  },
  {
    id: 'celtic-manor-twenty-ten',
    name: 'Celtic Manor Resort — Twenty Ten Course',
    region: 'Newport, Wales',
    teeName: 'White',
    courseRating: 74.6,
    slopeRating: 135,
    holes: [
      { par: 4, si: 11 },
      { par: 5, si: 3 },
      { par: 3, si: 13 },
      { par: 4, si: 15 },
      { par: 4, si: 1 },
      { par: 4, si: 7 },
      { par: 3, si: 17 },
      { par: 4, si: 9 },
      { par: 5, si: 5 },
      { par: 3, si: 18 },
      { par: 5, si: 8 },
      { par: 4, si: 4 },
      { par: 3, si: 14 },
      { par: 4, si: 2 },
      { par: 4, si: 12 },
      { par: 4, si: 6 },
      { par: 3, si: 16 },
      { par: 5, si: 10 },
    ],
  },
  {
    id: 'royal-liverpool',
    name: 'Royal Liverpool Golf Club — Hoylake',
    region: 'Wirral, England',
    teeName: 'Yellow',
    courseRating: 72.2,
    slopeRating: 139,
    holes: [
      { par: 4, si: 5 },
      { par: 4, si: 13 },
      { par: 5, si: 11 },
      { par: 3, si: 7 },
      { par: 4, si: 1 },
      { par: 4, si: 9 },
      { par: 3, si: 15 },
      { par: 5, si: 17 },
      { par: 4, si: 3 },
      { par: 4, si: 8 },
      { par: 3, si: 14 },
      { par: 4, si: 4 },
      { par: 3, si: 16 },
      { par: 5, si: 18 },
      { par: 4, si: 2 },
      { par: 5, si: 12 },
      { par: 4, si: 6 },
      { par: 4, si: 10 },
    ],
  },
  {
    id: 'royal-lytham-st-annes',
    name: "Royal Lytham & St Annes Golf Club",
    region: 'Lancashire, England',
    teeName: "Green (Men's)",
    courseRating: 72.5,
    slopeRating: 139,
    holes: [
      { par: 3, si: 13 },
      { par: 4, si: 5 },
      { par: 4, si: 1 },
      { par: 4, si: 9 },
      { par: 3, si: 15 },
      { par: 5, si: 7 },
      { par: 5, si: 3 },
      { par: 4, si: 11 },
      { par: 3, si: 17 },
      { par: 4, si: 10 },
      { par: 5, si: 4 },
      { par: 3, si: 14 },
      { par: 4, si: 18 },
      { par: 4, si: 6 },
      { par: 4, si: 2 },
      { par: 4, si: 16 },
      { par: 4, si: 8 },
      { par: 4, si: 12 },
    ],
  },
  {
    id: 'royal-birkdale',
    name: 'Royal Birkdale Golf Club',
    region: 'Southport, Merseyside, England',
    teeName: 'Yellow',
    courseRating: 72.6,
    slopeRating: 137,
    holes: [
      { par: 4, si: 11 },
      { par: 4, si: 3 },
      { par: 4, si: 7 },
      { par: 3, si: 15 },
      { par: 4, si: 13 },
      { par: 5, si: 1 },
      { par: 3, si: 17 },
      { par: 4, si: 9 },
      { par: 4, si: 5 },
      { par: 4, si: 14 },
      { par: 4, si: 8 },
      { par: 3, si: 18 },
      { par: 4, si: 4 },
      { par: 3, si: 16 },
      { par: 5, si: 2 },
      { par: 4, si: 12 },
      { par: 5, si: 6 },
      { par: 5, si: 10 },
    ],
  },
];

module.exports = { UK_COURSES };
